sonar.projectKey=myportfolio-pipeline
sonar.projectName=myportfolio-pipeline
sonar.projectVersion=1.0

# Sources : backend Node.js + frontend React
sonar.sources=backend,react/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/.git/**,**/build/**

# Encodage
sonar.sourceEncoding=UTF-8
