sonar.projectKey=myportfolio-pipeline
sonar.projectName=myportfolio-pipeline
sonar.projectVersion=2.0

# Sources analysées : code JS + manifestes Kubernetes YAML
sonar.sources=backend,react/src,k8s

# Exclusions : dépendances, fichiers compilés, git
sonar.exclusions=**/node_modules/**,**/dist/**,**/.git/**,**/build/**

sonar.sourceEncoding=UTF-8
