server {
    listen 80;

    # Resolver configurable via variable d environnement RESOLVER
    # Docker Compose : resolver 127.0.0.11 (DNS Docker interne)
    # Kubernetes     : resolver 10.96.0.10  (kube-dns)
    # La variable NGINX_RESOLVER est substituée au démarrage par envsubst
    resolver ${NGINX_RESOLVER} valid=10s;

    # Nom du backend : Docker=backend | Kubernetes=backend-service
    # Injecté via variable d environnement BACKEND_HOST
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri /index.html;
    }

    location /api {
        set $backend http://${BACKEND_HOST}:5000;
        proxy_pass         $backend;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }
}
